version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file: ./.env
    volumes:
      - ./src:/app/src:cached
    command: npm run start
